### PR TITLE
Added non-seekable stream support

### LINKED ISSUE #1: Replay relevant changes in develop branch since 2018/02/26
Since creating this repository and now there have been considerable changes in the develop branch:
* https://github.com/NetTopologySuite/NetTopologySuite/commit/4d99b0c28f9347ed706dfa448ef1d69e88e5214a

### PR DESCRIPTION
**Pull request by YohDeadfall**
Changes from https://github.com/NetTopologySuite/NetTopologySuite/pull/221 were lost due to refactoring (https://github.com/NetTopologySuite/NetTopologySuite/pull/229). Before merging this PR a new version of the main package must be released.

Fixes #1

### CODE REVIEW

**Comment by roji** [comment]
@FObermaier ping

**Comment by roji** [comment]
Guys, any chance to get this looked at and merged?

**Comment by YohDeadfall** [comment]
@FObermaier When will the next version with the fix be published?

**Comment by FObermaier** [comment]
@YohDeadfall could you test this one: 
https://www.myget.org/feed/nettopologysuite/package/nuget/NetTopologySuite.IO.PostGis
Thanks

**Comment by YohDeadfall** [comment]
Yes, will do.

**Comment by FObermaier** [comment]
> Yes, will do.

as in "I will test it" or "the package works"

**Comment by YohDeadfall** [comment]
I will test it (:

**Comment by YohDeadfall** [comment]
It works. Thanks! Ping me please when it is published on NuGet.

**Comment by FObermaier** [comment]
@YohDeadfall, short update, I wanted to push the package to nuget, then found out package id has been hijacked by some NHibernate.Spatial member. Awaiting to be added as owner. Sorry.

**Comment by FObermaier** [comment]
@YohDeadfall, @roji, I finally managed to push the package:
https://www.nuget.org/packages/NetTopologySuite.IO.PostGis/1.15.0

**Comment by roji** [comment]
Thanks @FObermaier!

Just released Npgsql.NetTopologySuite which depends on the new NetTopologySuite.IO.PostGis. Later I'll release Npgsql.EntityFrameworkCore.PostgreSQL.NTS which depends on that...

**Pull request merged**
